version: "3"
services:

   db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: oxefood
       POSTGRES_DB: oxefood
     ports:
       - 5433:5432
     volumes:
       - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: {}
